codecov:
  status:
    project:
      default:
        target: 80% # the required coverage value
  require_ci_to_pass: yes
  comment:
    layout: 'reach, diff, flags, files'
    behavior: default
    require_changes: false
    branches:
      - 'master'
