language: node_js

node_js:
  - 14.5.0

cache:
  directories:
    - 'node_modules'

notifications:
  email:
    on_success: never

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn run report
